--- #YAML:1.0
name:                WWW-Facebook-API
version:             0.4.13
abstract:            Facebook API implementation
license:             perl
author:              
    - David Romano <unobe@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Crypt::SSLeay:                 0
    Digest::MD5:                   0
    JSON::Any:                     0
    LWP::UserAgent:                0
    Readonly:                      0
    Time::HiRes:                   0
    version:                       0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
