# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WWW-Facebook-API
version:      0.4.14
version_from: lib/WWW/Facebook/API.pm
installdirs:  site
requires:
    Crypt::SSLeay:                 0
    Digest::MD5:                   0
    JSON::Any:                     0
    LWP::UserAgent:                0
    Readonly:                      0
    Time::HiRes:                   0
    version:                       0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
